baseurl = "http://abhiesa.github.io/"
languageCode = "en-hi"
title = "Blog @ abhiesa"
contentdir = "content"
datadir = "data"
publishdir = "public"
canonifyurls =  true
layoutdir = "layouts"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License (CC BY 4.0)."
copyrighturl = "http://creativecommons.org/licenses/by/4.0/"
PostFormat = true
disqusShortname = "abhiesasblog"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIdAnchors = true
  extensions = ["hardLineBreak","noEmptyLineBeforeBlock"]
  
[[menu.main]]
    name = "about"
    url = "/about/"
[[menu.main]]
    name = "archive"
    url = "/archive/"
[[menu.main]]
    name = "categories"
    url = "/categories/"
[[menu.main]]
    name = "tags"
    url = "/tags/"

[taxonomies]
  category = "categories"
  tag = "tags"
  
[permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:filename/"
	
paginate = 10
paginatepath = "page"

[indexes]
   category = "categories"
   tag = "tags"

[params]
  description = "Abhishek Pandey is a technical integration architect, with emphasis on specialized workflows and quality control with management. He has already scored big clients and employers by his side. He is also a father of little angle, and shares his birth date with his daughter. He commits himself as a passionate husband, loving son, and a proud indian citizen."
  author = "Abhishek Pandey"
  googleAnalytics = "UA-41826196-1"
  googleAuthorship = "113911752918942467189"
  theme = "no-js"
  defaultKeywords = "blog, golang, java, ecommerce, web app, spring, best practices, learning, tutorials, apache solr, apache lucene, elastic search, apache spark, apache mesos, apache zookeeper, private cloud, docker, vagrant"
  showTopProfile = true
  showTopSocial = false
  github = "abhiesa"
  linkedin = "abhiesa"
  googleplus = "113911752918942467189"
  facebook = "abhiesa"
  twitter = "abhiesa"
  youtube = "abhiesa"
  rss = true
  gravatarHash = "5dbab16d606f66592c2555df8eab8075"
  tagline = "Dream Design Desire Develop"
 
[Author]
  name = "Abhishek Pandey"

