baseurl = "http://abhiesa.github.io/"
languageCode = "en-us"
title = "My New Hugo Site"
contentdir = "content"
datadir = "data"
publishdir = "public"
canonifyurls =  true
layoutdir = "layouts"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License (CC BY 4.0)."
PostFormat = true
log = true
disqusShortname = "abhiesasblog"


[blackfriday]
  angledQuotes = true
  fractions = false
  plainIdAnchors = true
  extensions = ["hardLineBreak","noEmptyLineBeforeBlock"]
  
[[menu.main]]
    name = "saal"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "saal"
    url = "/saal/"
[[menu.main]]
    name = "about"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/about/"
[[menu.main]]
    name = "hello"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/hello/"

[taxonomies]
  category = "categories"
  tag = "tags"
  
[permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:filename/"
	
paginate = 10
paginatepath = "page"

[indexes]
   category = "categories"
   tag = "tags"

[params]
  defaultDescription = "Tesla's Awesome Hugo Site"
  author = "Nikola Tesla"
  highlight = "arta"
  googleAnalytics = "ABC"
  googleAuthorship = "LOL"
  theme = "no-js"
  defaultKeywords = "red, yellow, green"
  showTopProfile = true
  showTopSocial = false
  github = "abhiesa"
  bitbucket = "abhiesa"
  linkedin = "abhiesa"
  googleplus = "abhiesa"
  facebook = "abhiesa"
  twitter = "abhiesa"
  youtube = "abhiesa"
  rss = true
  gravatarHash = "5dbab16d606f66592c2555df8eab8075"
  tagline = "lala lala lori, doodh ki katoori"
 
[Author]
  name = "Abhi"

