baseurl = "http://abhiesa.github.io/"
languageCode = "en-us"
title = "Blog @ abhiesa"
contentdir = "content"
datadir = "data"
publishdir = "public"
canonifyurls =  true
layoutdir = "layouts"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License (CC BY 4.0)."
PostFormat = true
log = true
disqusShortname = "abhiesasblog"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIdAnchors = true
  extensions = ["hardLineBreak","noEmptyLineBeforeBlock"]
  
[[menu.main]]
    name = "about me"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about me"
    url = "/about/"

[taxonomies]
  category = "categories"
  tag = "tags"
  
[permalinks]
    post = "/:year/:month/:day/:filename/"
    page = "/:filename/"
	
paginate = 10
paginatepath = "page"

[indexes]
   category = "categories"
   tag = "tags"

[params]
  defaultDescription = "Dream Design Desire Develop"
  author = "Abhishek Pandey"
  highlight = "arta"
  #googleAnalytics = "ABC"
  googleAuthorship = "113911752918942467189"
  #theme = "no-js"
  defaultKeywords = "Dream Design Desire Develop"
  showTopProfile = true
  showTopSocial = false
  github = "abhiesa"
  #bitbucket = "abhiesa"
  linkedin = "abhiesa"
  googleplus = "113911752918942467189"
  facebook = "abhiesa"
  twitter = "abhiesa"
  youtube = "abhiesa"
  rss = true
  gravatarHash = "5dbab16d606f66592c2555df8eab8075"
  tagline = "Dream Design Desire Develop"
 
[Author]
  name = "Abhishek Pandey"
